### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by optozorax** [obeijaflor/physics-formula-sheet#1]
You document is awesome!!!
You should make a release with compiled `.pdf` file. It was very useful, anyone could download it without compilation.
![image](https://user-images.githubusercontent.com/18114381/27270538-1a1a4a00-54e9-11e7-90bf-bc402595917f.png)

---

What license of your document? Can anybody share it, modify?  

Sorry for bad English.

**Comment by rachelsfba** [comment]
Thanks! I'm glad it was useful to someone other than us. I forgot I even made this repository since I haven't had Physics in awhile, 

I've released our content under the BSD license. Hopefully there isn't much leftover content from other people's work. 

I added a `.pdf` to the Releases section as requested.

And your English is fine!

**Comment by optozorax** [comment]
# You should put `.pdf` file in this section when you make release
![image](https://user-images.githubusercontent.com/18114381/27451771-75bb0e84-57ba-11e7-92ae-ec24382424e8.png)

# Then it would be seems as
![image](https://user-images.githubusercontent.com/18114381/27451849-ba7d45dc-57ba-11e7-9130-74839d3c73b9.png)
